services:
  - type: web
    name: empleadossie
    rootDir: AppEmpleadosSIE_BEyFE
    env: docker
    plan: free
    buildCommand: |
      dotnet restore
      dotnet publish -c Release -o out
    startCommand: |
      dotnet out/AppEmpleadosSIE_BEyFE.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__Default
        sync: false   # para que lo agregues manualmente en el dashboard
      
